CREATE TABLE `success_stories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`userConsent` boolean NOT NULL DEFAULT false,
	`consentDate` timestamp,
	`anonymizationLevel` enum('full_name','first_name','initials','anonymous') NOT NULL DEFAULT 'first_name',
	`scoreBefore` int,
	`scoreAfter` int,
	`scoreIncrease` int,
	`accountsDeleted` int NOT NULL DEFAULT 0,
	`accountsVerified` int NOT NULL DEFAULT 0,
	`daysToResults` int,
	`testimonialText` text,
	`isAIGenerated` boolean NOT NULL DEFAULT true,
	`isPublished` boolean NOT NULL DEFAULT false,
	`isFeatured` boolean NOT NULL DEFAULT false,
	`displayName` varchar(100),
	`socialMediaImageUrl` text,
	`adminNotes` text,
	`approvedBy` int,
	`approvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `success_stories_id` PRIMARY KEY(`id`)
);
