name: disputestrike
region: nyc
services:
  - name: web
    github:
      repo: disputestrike/DisputeStrike
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        type: SECRET
      - key: JWT_SECRET
        type: SECRET
      - key: OPENAI_API_KEY
        type: SECRET
      - key: ANTHROPIC_API_KEY
        type: SECRET
      - key: STRIPE_SECRET_KEY
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        type: SECRET
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        type: SECRET
      - key: SENDGRID_API_KEY
        type: SECRET
      - key: SENDGRID_FROM_EMAIL
        value: noreply@disputestrike.com
      - key: ADMIN_EMAIL
        value: admin@disputestrike.com
    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      period_seconds: 30
