/**
 * PDF Generator for Dispute Letters
 * 
 * Converts generated dispute letters into professional PDFs
 */

import puppeteer from "puppeteer";

export interface LetterPDFOptions {
  letterContent: string;
  userInfo: {
    name: string;
    address: string;
  };
  bureau: 'TransUnion' | 'Equifax' | 'Experian';
  date: Date;
}

/**
 * Generate PDF from letter content
 * This is a server-side implementation that returns HTML for PDF conversion
 */
export function generateLetterHTML(options: LetterPDFOptions): string {
  const { letterContent, userInfo, bureau, date } = options;

  const bureauAddresses = {
    TransUnion: 'TransUnion LLC\\nConsumer Dispute Center\\nP.O. Box 2000\\nChester, PA 19016-2000',
    Equifax: 'Equifax Information Services LLC\\nP.O. Box 740256\\nAtlanta, GA 30374-0256',
    Experian: 'Experian\\nP.O. Box 4500\\nAllen, TX 75013',
  };

  // Format the letter content (preserve formatting)
  const formattedContent = letterContent
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/__(.*?)__/g, '<em>$1</em>');

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>FCRA Dispute Letter - ${bureau}</title>
  <style>
    @page {
      size: letter;
      margin: 1in;
    }
    
    body {
      font-family: 'Times New Roman', Times, serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #000;
      max-width: 6.5in;
      margin: 0 auto;
    }
    
    .letterhead {
      text-align: right;
      margin-bottom: 2em;
    }
    
    .letterhead .date {
      font-weight: bold;
    }
    
    .recipient {
      margin-bottom: 2em;
    }
    
    .subject {
      font-weight: bold;
      text-decoration: underline;
      margin: 2em 0 1em 0;
      text-align: center;
    }
    
    .content p {
      margin: 1em 0;
      text-align: justify;
    }
    
    .signature {
      margin-top: 3em;
    }
    
    .signature-line {
      border-top: 1px solid #000;
      width: 200px;
      margin-top: 3em;
    }
    
    strong {
      font-weight: bold;
    }
    
    em {
      font-style: italic;
    }
    
    .account-section {
      margin: 1.5em 0;
      padding-left: 1em;
    }
    
    .violation-list {
      margin-left: 2em;
    }
    
    .footer {
      margin-top: 2em;
      font-size: 10pt;
      text-align: center;
      color: #666;
    }
  </style>
</head>
<body>
  <div class="letterhead">
    <div>${userInfo.name}</div>
    <div>${userInfo.address.replace(/\n/g, '<br>')}</div>
    <div class="date">${date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
  </div>

  <div class="recipient">
    <div>${bureauAddresses[bureau].replace(/\\n/g, '<br>')}</div>
  </div>

  <div class="subject">
    RE: FORMAL DISPUTE OF INACCURATE INFORMATION UNDER FCRA § 1681i
  </div>

  <div class="content">
    <p>${formattedContent}</p>
  </div>

  <div class="signature">
    <p>Sincerely,</p>
    <div class="signature-line"></div>
    <p>${userInfo.name}</p>
  </div>

  <div class="footer">
    <p>This letter is sent via Certified Mail with Return Receipt Requested</p>
    <p>Generated by DisputeStrike - FCRA Compliance Software</p>
  </div>
</body>
</html>
  `.trim();
}

/**
 * Generate mailing label HTML
 */
export function generateMailingLabelHTML(
  fromAddress: string,
  toAddress: string,
  bureau: 'TransUnion' | 'Equifax' | 'Experian'
): string {
  const bureauAddresses = {
    TransUnion: 'TransUnion LLC\nConsumer Dispute Center\nP.O. Box 2000\nChester, PA 19016-2000',
    Equifax: 'Equifax Information Services LLC\nP.O. Box 740256\nAtlanta, GA 30374-0256',
    Experian: 'Experian\nP.O. Box 4500\nAllen, TX 75013',
  };

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    @page {
      size: 4in 3in;
      margin: 0.25in;
    }
    
    body {
      font-family: Arial, sans-serif;
      font-size: 11pt;
    }
    
    .from-address {
      margin-bottom: 1in;
      font-size: 10pt;
    }
    
    .to-address {
      font-size: 12pt;
      font-weight: bold;
    }
    
    .certified-mail {
      margin-top: 0.5in;
      text-align: center;
      font-weight: bold;
      text-decoration: underline;
    }
  </style>
</head>
<body>
  <div class="from-address">
    ${fromAddress.replace(/\n/g, '<br>')}
  </div>
  
  <div class="to-address">
    ${bureauAddresses[bureau].replace(/\n/g, '<br>')}
  </div>
  
  <div class="certified-mail">
    CERTIFIED MAIL - RETURN RECEIPT REQUESTED
  </div>
</body>
</html>
  `.trim();
}

/**
 * Generate exhibits page (list of supporting documents)
 */
export function generateExhibitsHTML(exhibits: string[]): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    @page {
      size: letter;
      margin: 1in;
    }
    
    body {
      font-family: 'Times New Roman', Times, serif;
      font-size: 12pt;
      line-height: 1.6;
    }
    
    h1 {
      text-align: center;
      text-decoration: underline;
      margin-bottom: 2em;
    }
    
    .exhibit-list {
      margin-left: 2em;
    }
    
    .exhibit-item {
      margin: 1em 0;
    }
  </style>
</head>
<body>
  <h1>EXHIBITS</h1>
  
  <div class="exhibit-list">
    ${exhibits.map((exhibit, index) => `
      <div class="exhibit-item">
        <strong>Exhibit ${String.fromCharCode(65 + index)}:</strong> ${exhibit}
      </div>
    `).join('')}
  </div>
</body>
</html>
  `.trim();
}

/**
 * Get standard exhibits list
 */
/**
 * Generate actual PDF buffer using Puppeteer
 */
export async function generateLetterPDF(options: LetterPDFOptions): Promise<Buffer> {
  const html = generateLetterHTML(options);
  
  const browser = await puppeteer.launch({
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-gpu',
    ],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });

    const pdfBuffer = await page.pdf({
      format: 'letter',
      printBackground: true,
      margin: {
        top: '1in',
        right: '1in',
        bottom: '1in',
        left: '1in',
      },
    });

    return Buffer.from(pdfBuffer);
  } finally {
    await browser.close();
  }
}

export function getStandardExhibits(bureau: 'TransUnion' | 'Equifax' | 'Experian'): string[] {
  return [
    'Copy of government-issued photo identification (Passport)',
    'Proof of current address (Utility bill)',
    `Copy of ${bureau} credit report with disputed items highlighted`,
    'Copy of Equifax credit report (for cross-bureau comparison)',
    'Copy of Experian credit report (for cross-bureau comparison)',
    'Copy of TransUnion credit report (for cross-bureau comparison)',
  ].filter((_, index) => {
    // Don't include the bureau's own report twice
    if (index === 2) return true;
    if (index === 3 && bureau !== 'Equifax') return true;
    if (index === 4 && bureau !== 'Experian') return true;
    if (index === 5 && bureau !== 'TransUnion') return true;
    return index < 2;
  });
}
